# Generated by Django 5.0 on 2024-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserCred', models.IntegerField()),
                ('Department', models.CharField(max_length=200)),
                ('Course', models.CharField(max_length=200)),
                ('Code', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
